modelType: collectionType
collectionName: users
info:
  displayName: Users
  singularName: user
  pluralName: users
  description:
attributes:
  name:
    type: string
    unique: true
    notNullable: true
  active:
    type: boolean
    notNullable: true